CREATE TABLE if not exists USERS (
USER_ID		    SERIAL  PRIMARY KEY,
USER_NAME		VARCHAR(100) NOT NULL,
USER_EMAIL		VARCHAR(100) NOT NULL,
USER_PASSWORD	VARCHAR(100) NOT NULL,
USER_TYPE	    VARCHAR(20)  NOT NULL
);

CREATE TABLE if not exists BOOKS (
BOOK_ID		    SERIAL  PRIMARY KEY,
BOOK_NAME		VARCHAR(100) NOT NULL,
AUTHOR_NAME		VARCHAR(100) NOT NULL,
PUBLISHING_YEAR	SMALLINT,
PUBLISHER	    VARCHAR(100),
DESCRIPTION	    VARCHAR(200),
RETAIL_PRICE	NUMERIC(200),
URL	            VARCHAR(100)
);

CREATE TABLE if not exists REVIEWS (
REVIEW_ID	SERIAL PRIMARY KEY,
RATING	SMALLINT NOT NULL,
REVIEW	VARCHAR(200) NOT NULL,
DATE_AND_TIME	TIMESTAMP NOT NULL,
USER_ID	INT,
BOOK_ID	INT,
FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID)
);

CREATE TABLE if not exists IMAGES (
IMAGE_ID	SERIAL PRIMARY KEY,
BOOK_IMAGE	BYTEA NOT NULL,
USER_ID	INT,
BOOK_ID	INT,
FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID)
);

CREATE TABLE if not exists FOLLOWINGS (
FOLLOWING_ID	SERIAL PRIMARY KEY,
USER_ID	INT,
FOLLOWED_ID	INT,
FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
FOREIGN KEY (FOLLOWED_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE if not exists LIKES (
LIKE_ID	SERIAL PRIMARY KEY,
USER_ID	INT,
REVIEW_ID	INT,
FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
FOREIGN KEY (REVIEW_ID) REFERENCES REVIEWS (REVIEW_ID)
);

